#!/usr/bin/env python

import os
import re
import sys

ext_desc = {'.$01' : u'DOS Pipe File', 
			'.001' : u'Multimedia Fusion Backup File', 
			'.4db' : u'4th Dimension Database Structure File', 
			'.4th' : u'Forth Language File', 
			'.a' : u'Static Library', 
			'.a2w' : u'Alice World', 
			'.ab' : u'Applix Builder File', 
			'.abc' : u'ABC Source File', 
			'.abc' : u'ActionScript Byte Code File', 
			'.acd' : u'RSLogix 5000 Program', 
			'.acp' : u'EditPlus Auto-Completion File', 
			'.act' : u'DS Game Maker Action File', 
			'.actx' : u'DS Game Maker Action Description File', 
			'.ada' : u'Ada Source Code', 
			'.adb' : u'Ada Body File', 
			'.adblock' : u'Alpha Five Library Temporary File', 
			'.addin' : u'Visual Studio Add-in Definition File', 
			'.ads' : u'Ada Specification File', 
			'.agi' : u'Asterisk Gateway Interface File', 
			'.alb' : u'Alpha Five Library', 
			'.alm' : u'Alpha Five Library', 
			'.alp' : u'AnyLogic Project File', 
			'.alx' : u'Alpha Five Library Index File', 
			'.am' : u'Automake Makefile Template', 
			'.am4' : u'AutoPlay Media Studio 4 Project File', 
			'.am5' : u'AutoPlay Media Studio 5 Project File', 
			'.am6' : u'AutoPlay Media Studio 6 Project', 
			'.am7' : u'AutoPlay Media Studio 7 Project', 
			'.aml' : u'Abstract Markup Language', 
			'.aml' : u'Arc Macro Language File', 
			'.ane' : u'Adobe AIR Native Extension', 
			'.anjuta' : u'Anjuta IDE Project File', 
			'.ap_' : u'ADT Android Developer Package', 
			'.apa' : u'RSView Development Project Archive', 
			'.applet' : u'Eclipse Java Applet Policy File', 
			'.appx' : u'Windows 8 App Package ', 
			'.appxsym' : u'Windows 8 App Package Symbols File', 
			'.appxupload' : u'Windows 8 App Upload Package', 
			'.apr' : u'Apadana Project File', 
			'.aps' : u'Visual C++ Resource File', 
			'.arr' : u'MultiMedia Fusion Array File', 
			'.arsc' : u'Android Package Resource File', 
			'.art' : u'Artifacts Artifact File', 
			'.artproj' : u'Artifacts Project', 
			'.as' : u'ActionScript File', 
			'.as2proj' : u'FlashDevelop ActionScript 2 Project File', 
			'.as3proj' : u'FlashDevelop ActionScript 3 Project File', 
			'.asc' : u'ActionScript Communication File', 
			'.ascs' : u'ActionScript Communication Server File', 
			'.asdb' : u'Asphyre Sphinx Archive File', 
			'.asi' : u'Alpha Five Variable File', 
			'.asm' : u'Visual Studio Assembler Source Code File', 
			'.asm' : u'Assembly Language Source Code File', 
			'.asvf' : u'Asphyre Sphinx Archive File', 
			'.asx' : u'Alpha Five Library Temporary Index File', 
			'.au3' : u'AutoIt v3 Script', 
			'.aut' : u'AutoIt Script File', 
			'.autoplay' : u'AutoPlay Media Studio Project File', 
			'.awk' : u'AWK Script', 
			'.axe' : u'Annotated XML Example File', 
			'.b' : u'BuRg3r Definition File', 
			'.b' : u'BASIC Source File', 
			'.bas' : u'BASIC Source Code File', 
			'.basex' : u'BaseX Data File', 
			'.bb' : u'Blitz Source Code File', 
			'.bbc' : u'BBC BASIC Data File', 
			'.bbproject' : u'BBEdit Project File', 
			'.bbprojectd' : u'BBEdit Project Document', 
			'.bcp' : u'Borland C++ Makefile', 
			'.bdsproj' : u'Borland Developer Studio Project', 
			'.bet' : u'BETA Source File', 
			'.bluej' : u'BlueJ Package File', 
			'.bpg' : u'Borland Project Group', 
			'.bpl' : u'Borland Package Library', 
			'.bpr' : u'Borland C++Builder Project File', 
			'.brx' : u'BREW Application Resource File', 
			'.bs2' : u'BASIC Stamp 2 Code File', 
			'.bsc' : u'Visual Studio Source Browser Information File', 
			'.bsh' : u'BeanShell Script', 
			'.btn' : u'AutoPlay Media Studio Button File', 
			'.buildpath' : u'Eclipse Build Path File', 
			'.bur' : u'BuRg3r Source Code File', 
			'.bytes' : u'Binary Text Asset Data File', 
			'.c' : u'C/C++ Source Code File', 
			'.c' : u'Lite-C Script', 
			'.caf' : u'CryENGINE Character Animation File', 
			'.cap' : u'Construct Game Development File', 
			'.caproj' : u'Construct Project File', 
			'.capx' : u'Construct Compressed Project File', 
			'.car' : u'Brew Component Application Resource File', 
			'.cba' : u'CryENGINE Resource Compiler Settings File', 
			'.cbl' : u'COBOL Source Code File', 
			'.cbp' : u'Code::Blocks Project File', 
			'.cc' : u'C++ Source Code File', 
			'.ccgame' : u'XNA Creators Club Game Package', 
			'.ccn' : u'Compressed Multimedia Fusion File', 
			'.ccp' : u'CodeCharge Studio Page File', 
			'.ccs' : u'CodeCharge Studio Project File', 
			'.ccscc' : u'ClearCase Source Control Info File', 
			'.cd' : u'Visual Studio Class Diagram', 
			'.cdf' : u'CryENGINE Character Definition File', 
			'.cdx' : u'Alpha Five Table Index File', 
			'.cdxml' : u'Cmdlet Definition XML File', 
			'.cfc' : u'ColdFusion Component File', 
			'.cham' : u'Compiled HAM File', 
			'.chef' : u'Chef Source Code File', 
			'.ci' : u'PolySpace Preprocessed Code File', 
			'.ckbx' : u'Cricket Audio XML Bank Description File', 
			'.class' : u'Java Class File', 
			'.clips' : u'Coda Clips File', 
			'.cls' : u'Program Class File', 
			'.clw' : u'Visual C++ ClassWizard File', 
			'.cma' : u'OCaml Library', 
			'.cob' : u'COBOL Source Code File', 
			'.cod' : u'Compiled Source Code', 
			'.config' : u'Configuration File', 
			'.cp' : u'Xcode C++ Source File', 
			'.cp' : u'Captivate Source File', 
			'.cpb' : u'Comicino Studio Project File', 
			'.cpp' : u'C++ Source Code File', 
			'.cs' : u'Visual C# Source Code File', 
			'.csi' : u'ContentServ Include File', 
			'.csi' : u'EdLog Program Data File', 
			'.csn' : u'Adobe Code Snippet Document', 
			'.csp' : u'Cache Server Page', 
			'.csproj' : u'Visual Studio C# Project', 
			'.cst' : u'ContentServ Template', 
			'.csx' : u'Visual C# Script', 
			'.ctc' : u'Visual Studio Command Table Configuration File', 
			'.ctl' : u'Visual Basic UserControl Object File', 
			'.cto' : u'Visual Studio Binary Command Table Output File', 
			'.ctp' : u'CakePHP Template', 
			'.ctsym' : u'Visual Studio Command Table Output File', 
			'.ctx' : u'Visual Basic Control Binary File', 
			'.ctxt' : u'BlueJ Context File', 
			'.cu' : u'CUDA Source Code File', 
			'.cvsrc' : u'CVS Command File', 
			'.cxp' : u'CX-Programmer Project File', 
			'.cxt' : u'CX-Programmer Project Text File', 
			'.cxx' : u'C++ Source Code File', 
			'.d' : u'D Source Code File', 
			'.dabriefcase' : u'RemObjects Data Abstract File Briefcase', 
			'.daconfig' : u'RemObjects Data Abstract Configuration File', 
			'.dba' : u'DarkBASIC Source Code File', 
			'.dba' : u'CryENGINE Animation Database File', 
			'.dbml' : u'Visual Studio OR Design File', 
			'.dbo' : u'DarkBASIC Object', 
			'.dbpro' : u'DarkBASIC Professional Project File', 
			'.dbproj' : u'Visual Studio Database Project File', 
			'.dcp' : u'Delphi Compiled Package', 
			'.dcproj' : u'Dashcode Project', 
			'.dcu' : u'Delphi Compiled Unit', 
			'.dcuil' : u'Delphi .NET Compiled Unit File', 
			'.ddd' : u'Alpha Five Data Dictionary File', 
			'.ddm' : u'Alpha Five Data Dictionary Memo File', 
			'.ddp' : u'Delphi Diagram Portfolio File', 
			'.ddx' : u'Alpha Five Data Dictionary Index File', 
			'.dec' : u'Declaration File', 
			'.def' : u'Module-Definition File', 
			'.defs' : u'BlueJ Settings File', 
			'.dep' : u'Windows Dependency File', 
			'.depend' : u'Code::Blocks Dependencies File', 
			'.dev' : u'Dev-C++ Project File', 
			'.developerprofile' : u'Xcode Developer Profile', 
			'.deviceids' : u'Device Identification FIle', 
			'.dex' : u'Dalvik Executable File', 
			'.df1' : u'Omnis Native Datafile', 
			'.dfk' : u'Dark Flow Project File', 
			'.dfm' : u'Delphi Form', 
			'.dgml' : u'Visual Studio Directed Graph Document', 
			'.dgsl' : u'Visual Shader Graph File', 
			'.diff' : u'Patch File', 
			'.dis' : u'DisSharp Project File', 
			'.dm1' : u'ER/Studio Data Model File', 
			'.dmd' : u'SQL Developer Data Modeler File', 
			'.dob' : u'Visual Basic UserDocument', 
			'.docset' : u'Doxygen Document Set File', 
			'.dox' : u'Visual Basic Binary UserDocument', 
			'.dox' : u'Doxygen Documentation File', 
			'.dpk' : u'Delphi Package', 
			'.dpkw' : u'Delphi Package', 
			'.dpl' : u'Delphi Package Library', 
			'.dpr' : u'Delphi Project', 
			'.dproj' : u'Delphi Project', 
			'.dres' : u'Delphi Compiled Resource File', 
			'.drf' : u'Delphi Resource File', 
			'.dsgm' : u'DS Game Maker Project', 
			'.dsk' : u'Borland Project Desktop File', 
			'.dsp' : u'Visual C++ 6 Project', 
			'.dsym' : u'Xcode Debug Symbols File', 
			'.dtd' : u'Document Type Definition File', 
			'.dylib' : u'Mach-O Dynamic Library', 
			'.ecp' : u'EasyC Project File', 
			'.edm' : u'Adobe Extension Data Markup Language File', 
			'.edml' : u'Adobe Extension Data Markup Language Document', 
			'.edmx' : u'ADO.NET Entity Data Model Designer File', 
			'.el' : u'Emacs Lisp Code File', 
			'.elc' : u'Emacs Compiled Lisp File', 
			'.ent' : u'External Entity', 
			'.entitlements' : u'Mac App Sandboxing Entitlements File', 
			'.eql' : u'Embedded SQL File', 
			'.erb' : u'Ruby ERB Script', 
			'.erl' : u'Erlang Source Code File', 
			'.ex' : u'Euphoria Source Code', 
			'.exl' : u'JSDAI Inclusion or Exclusion List', 
			'.exp' : u'Symbols Export File', 
			'.exw' : u'Euphoria Source code File', 
			'.f' : u'Fortran Source Code', 
			'.f90' : u'Fortran 90 Source Code File', 
			'.fbp' : u'wxFormBuilder Project', 
			'.fbp7' : u'FinalBuilder 7 Project', 
			'.fbz7' : u'Compressed FinalBuilder 7 Project', 
			'.fce' : u'ForeUI Custom Element File', 
			'.fcl' : u'ForeUI Custom Library File', 
			'.fd' : u'DataFlex Data File', 
			'.feature' : u'SharePoint Feature File', 
			'.fgl' : u'Fifth Generation Language Source File', 
			'.filters' : u'Visual C++ Project Filters File', 
			'.fimpp' : u'FiM++ Source Code File', 
			'.fla' : u'Adobe Flash Animation', 
			'.for' : u'Fortran 77 Source File', 
			'.forth' : u'Forth Language File', 
			'.fpm' : u'FPS Creator Map File', 
			'.fpp' : u'Fortran Source Code', 
			'.fpt' : u'Alpha Five Table Memo File', 
			'.framework' : u'Mac OS X Application Framework', 
			'.frj' : u'FreeForm-J Project File', 
			'.frm' : u'Visual Basic Text Form', 
			'.frx' : u'Visual Basic Binary Form File', 
			'.frx' : u'FoxPro Report', 
			'.fs' : u'Visual F# Source File', 
			'.fsi' : u'Visual F# Signature File', 
			'.fsl' : u'Form Z Script', 
			'.fsproj' : u'Visual F# Project File', 
			'.fsproj' : u'FireStarter Project File', 
			'.fsscript' : u'Visual F# Script', 
			'.fsx' : u'Visual F# Script File', 
			'.ftl' : u'FreeMarker Template File', 
			'.ftn' : u'Fortran Source Code File', 
			'.fxc' : u'FilePackager Configuration', 
			'.fxcproj' : u'FX Composer Project File', 
			'.fxl' : u'FaceFX Language File', 
			'.fxml' : u'FXML Source Code File', 
			'.fxpl' : u'Adobe Flash FXP Library', 
			'.gameproj' : u'GameSalad Project File', 
			'.gar' : u'GridGain Archive', 
			'.gbap' : u'GLBasic Project File', 
			'.gbas' : u'GLBasic Source File', 
			'.gch' : u'Precompiled Header File', 
			'.gdfmakerproject' : u'GDF Editor Project File', 
			'.ged' : u'Game Editor Project File', 
			'.gem' : u'RubyGems Package', 
			'.gemspec' : u'Gem Specification File', 
			'.gfar' : u'Greenfoot Archive', 
			'.gitattributes' : u'Git Attributes File', 
			'.gitignore' : u'Git Ignore File', 
			'.glade' : u'Glade Project File', 
			'.gld' : u'MPLAB C Compiler Linker Script File', 
			'.global' : u'Global Makefile', 
			'.gls' : u'GLScript Game Script', 
			'.gm' : u'GameMonkey Script', 
			'.gm6' : u'Game Maker 6 Project File', 
			'.gm81' : u'Game Maker 8.1 Project File', 
			'.gmd' : u'Game Maker Program Code', 
			'.gmk' : u'Game Maker Project File', 
			'.gml' : u'Game Maker Language File', 
			'.gmo' : u'GNU Machine Object File', 
			'.gnumakefile' : u'GNU Makefile', 
			'.gorm' : u'Gorm Interface Resource File', 
			'.gpj' : u'jGRASP Project File', 
			'.gpj' : u'MULTI IDE Project File', 
			'.greenfoot' : u'Greenfoot Project Archive', 
			'.groovy' : u'Groovy Source Code File', 
			'.groupproj' : u'Delphi Project Group File', 
			'.gs' : u'Google Apps Script', 
			'.gs3' : u'GameStarter File', 
			'.gsproj' : u'GameSalad Windows Project File', 
			'.gszip' : u'GameSalad Marketplace Asset File', 
			'.gvy' : u'Groovy Source Code File', 
			'.h' : u'C/C++/Objective-C Header File', 
			'.hal' : u'HansaWorld Application Language File', 
			'.handlebars' : u'Handlebars Template', 
			'.has' : u'Haskell Script', 
			'.hbs' : u'Handlebars Template', 
			'.hcf' : u'Compact Ham Library', 
			'.hh' : u'C++ Header File', 
			'.hhh' : u'Power C Precompiled Header File', 
			'.hpf' : u'High Performance Fortran File', 
			'.hpp' : u'C++ Header File', 
			'.hrl' : u'Erlang Header File', 
			'.hs' : u'Haskell Script', 
			'.hxx' : u'C++ Source Code Header File', 
			'.hydra' : u'Hydra Image Filter Program File', 
			'.i' : u'Visual Studio Intermediate File', 
			'.i' : u'INTERCAL Source File', 
			'.idb' : u'Visual Studio Intermediate Debug File', 
			'.idl' : u'Interface Definition Language File', 
			'.idt' : u'Windows Installer Database Text Archive File', 
			'.ilk' : u'Incremental Linking File', 
			'.iml' : u'IntelliJ IDEA Module', 
			'.inc' : u'Include File', 
			'.inl' : u'C++ Inline File', 
			'.ino' : u'Arduino Sketch File', 
			'.ipch' : u'Intellisense Precompiled Header File', 
			'.ipp' : u'Inline Guard Macro File', 
			'.ipr' : u'IntelliJ IDEA Project File', 
			'.ipr' : u'InstallShield Professional Project File', 
			'.isc' : u'Xilinx Device Configuration File', 
			'.ise' : u'InstallShield Express Project File', 
			'.ism' : u'InstallShield Project File', 
			'.ist' : u'InstallShield Project Template File', 
			'.iws' : u'IntelliJ IDEA Web Page', 
			'.iwz' : u'InstallShield Express 2 Project File', 
			'.j' : u'Java Source File', 
			'.jav' : u'Java Source File', 
			'.java' : u'Java Source Code File', 
			'.jcp' : u'JCreator Project File', 
			'.jed' : u'Xilinx JEDEC Programming File', 
			'.jic' : u'JTAG Indirect Configuration File', 
			'.jl' : u'Julia Source Code File', 
			'.jnilib' : u'JNI Library', 
			'.jpd' : u'Java Process Definition', 
			'.jpr' : u'JBuilder Project', 
			'.jpx' : u'JBuilder Project', 
			'.jsfl' : u'Flash JavaScript File', 
			'.jsh' : u'JAWS Script Header File', 
			'.jsh' : u'Jsh Script', 
			'.jspf' : u'Java Server Page Fragment', 
			'.jss' : u'JAWS Script', 
			'.jsxinc' : u'ExtendScript Included Script File', 
			'.kb' : u'C++ Keyboard Script', 
			'.kdevdlg' : u'KDevelop Dialog Box File', 
			'.kdevelop' : u'KDevelop Project Data File', 
			'.kdevprj' : u'KDevelop Project File', 
			'.kdmp' : u'Windows Crash Dump File', 
			'.kpl' : u'Kids Programming Language File', 
			'.l' : u'Lex Source File', 
			'.lbi' : u'Dreamweaver Library Item', 
			'.lbs' : u'Omnis Library', 
			'.lds' : u'Binutils LD Linker Script', 
			'.lgo' : u'Logo Instructions File', 
			'.lhs' : u'Literate Haskell Script', 
			'.licenses' : u'Visual Studio Licensed Classes File', 
			'.licx' : u'Visual Studio License File', 
			'.lis' : u'VAX Program Listing', 
			'.lisp' : u'Lisp Source Code File', 
			'.list' : u'JAR Index File', 
			'.lit' : u'Literate Haskell Script', 
			'.lit' : u'Lit Source Code File', 
			'.livecode' : u'LiveCode Stack File', 
			'.lnt' : u'PC-lint/FlexeLint Configuration File', 
			'.lol' : u'LOLCODE Source Code FIle', 
			'.lproj' : u'Localized Project Folder', 
			'.lrdb' : u'Photoshop Lightroom Database', 
			'.lrf' : u'Microsoft Linker Response File', 
			'.lsp' : u'Lisp Program Source Code File', 
			'.lsproj' : u'Visual Studio LightSwitch Project', 
			'.ltb' : u'LithTech Binary File', 
			'.lua' : u'Lua Source File', 
			'.lucidsnippet' : u'Lucid Snippet File', 
			'.lxsproj' : u'Liquid XML Studio Project File', 
			'.m' : u'MATLAB Source Code File', 
			'.m' : u'Mercury Source Code File', 
			'.m' : u'Objective-C Implementation File', 
			'.m4' : u'Macro Processor Library', 
			'.magik' : u'Magik Source Code File', 
			'.mak' : u'Makefile', 
			'.make' : u'Xcode Makefile Script', 
			'.makefile' : u'Makefile', 
			'.mako' : u'Mako Template', 
			'.markdn' : u'Markdown File', 
			'.markdown' : u'Markdown Documentation File', 
			'.mcp' : u'CodeWarrior Project', 
			'.md' : u'Markdown Documentation File', 
			'.md' : u'Machine Description File', 
			'.mdown' : u'Markdown File', 
			'.mdzip' : u'MagicDraw Project Archive', 
			'.med' : u'RSView Development Project', 
			'.mer' : u'RSView Development Runtime File', 
			'.mf' : u'Java Manifest File', 
			'.mfa' : u'Multimedia Fusion Development File', 
			'.mfcribbon-ms' : u'MFC Ribbon Definition XML File', 
			'.mk' : u'Makefile', 
			'.ml' : u'ML Source Code File', 
			'.mlb' : u'Visual FoxPro Library', 
			'.mm' : u'Objective-C++ Source File', 
			'.mo' : u'Machine Object File', 
			'.mod' : u'Fortran Module File', 
			'.mom' : u'Managed Object Model', 
			'.mpr' : u'FoxPro Generated Menu Program', 
			'.mrt' : u'Stimulsoft Report File', 
			'.msha' : u'Microsoft Help Asset File', 
			'.mshc' : u'Microsoft Help Container File ', 
			'.mshi' : u'Microsoft Help Index File', 
			'.msl' : u'Mapping Specification Language File', 
			'.msp' : u'MaxScript Page File', 
			'.mss' : u'Microprocessor Software Specification File', 
			'.mv' : u'MivaScript File', 
			'.mvx' : u'Multimedia Fusion Movement Extension', 
			'.mxml' : u'Flex MXML Component', 
			'.myapp' : u'Visual Studio Application XML File', 
			'.nbc' : u'Next Byte Codes Source Code File', 
			'.ncb' : u'Visual C++ IntelliSense Database', 
			'.ned' : u'OMNeT++ Network Description File', 
			'.neko' : u'Neko Source Code File', 
			'.nfm' : u'Delphi .NET Form File', 
			'.nib' : u'Interface Builder User Interface File', 
			'.nim' : u'Nimrod Source Code File', 
			'.nk' : u'NUKE Script', 
			'.nls' : u'NetLogo Source File', 
			'.nqc' : u'Not Quite C Source Code File', 
			'.nsh' : u'NSIS Header File', 
			'.nsi' : u'NSIS Script', 
			'.nupkg' : u'NuGet Package', 
			'.nuspec' : u'NuGet Specification File', 
			'.nvv' : u'NVIDIA Vertex Shader File', 
			'.nxc' : u'Not eXactly C Source Code File', 
			'.o' : u'Compiled Object File', 
			'.oca' : u'Custom Control Library Type File', 
			'.octest' : u'Xcode Objective-C Unit Test Bundle', 
			'.ocx' : u'ActiveX Control', 
			'.odl' : u'Object Description Language File', 
			'.omo' : u'OMake Object File', 
			'.orderedtest' : u'Visual Studio Ordered Test File', 
			'.os' : u'ObjectScript Source File', 
			'.osc' : u'Obix Source Code File', 
			'.ow' : u'Free Pascal 1.0.x Object File', 
			'.owl' : u'OWL Source Code File', 
			'.oxygene' : u'Oxygene Project File', 
			'.p' : u'Pascal Source Code', 
			'.p' : u'Python Pickle File', 
			'.p3d' : u'Panda3D Multifile ', 
			'.p6' : u'Perl 6 Source Code File', 
			'.pas' : u'Pascal Source File', 
			'.pas' : u'Delphi Unit Source File', 
			'.patch' : u'Patch File', 
			'.pb' : u'PureBasic Source File', 
			'.pbg' : u'Pixel Bender Graph File', 
			'.pbj' : u'Pixel Bender Bytecode File', 
			'.pbk' : u'Pixel Bender Kernel File', 
			'.pbproj' : u'Project Builder Project', 
			'.pbxbtree' : u'Xcode Auto-Complete File', 
			'.pbxproj' : u'Xcode Project Data File', 
			'.pbxuser' : u'Xcode Project User Data File', 
			'.pc' : u'Pro*C Source Code File', 
			'.pch' : u'Precompiled Header File', 
			'.pcp' : u'Windows Installer Patch Creation Properties File', 
			'.pde' : u'Processing Development Environment Source Code File', 
			'.pde' : u'Arduino Sketch', 
			'.pdl' : u'Perl Data Language File', 
			'.pdm' : u'VB Project Information File', 
			'.pfg' : u'jEEPers Program Configuration File', 
			'.ph' : u'Perl Header File', 
			'.pickle' : u'Python Pickle File', 
			'.pika' : u'Pika Software Builder Project File', 
			'.pjx' : u'FoxPro Project', 
			'.pkgdef' : u'Visual Studio Shell File', 
			'.pkgundef' : u'Visual Studio Shell File', 
			'.pl' : u'Prolog Source Code File', 
			'.pl' : u'Perl Script', 
			'.pl1' : u'PL/I Source Code', 
			'.plc' : u'PL/B Source File', 
			'.ple' : u'Messenger Plus! Live Encrypted Log File', 
			'.plg' : u'Visual Studio Build Log File', 
			'.pli' : u'PL/I Source Code File', 
			'.pltsuite' : u'Safari Page Load Test Suite File', 
			'.pm' : u'Perl Module', 
			'.pmq' : u'Microsoft Target Analyzer File', 
			'.pnt' : u'Panther Project', 
			'.po' : u'Portable Object', 
			'.pod' : u'Perl POD File', 
			'.pom' : u'Maven Build File', 
			'.pot' : u'Portable Object File', 
			'.ppc' : u'Mobile Data Studio Project File', 
			'.ppl' : u'Free Pascal Dynamic Library', 
			'.ppu' : u'Free Pascal Unit File', 
			'.prg' : u'Visual FoxPro Program File', 
			'.prg' : u'RPG Toolkit Program File', 
			'.prg' : u'xBase Program File', 
			'.prg' : u'RAPID Program File', 
			'.pri' : u'Qt Project Include File', 
			'.pri' : u'Windows Compiled Resources File', 
			'.pro' : u'Qt Project File', 
			'.project' : u'Eclipse Project Settings File', 
			'.proto' : u'Protocol Buffer File', 
			'.psd1' : u'Windows PowerShell Data File', 
			'.psess' : u'Visual Studio Performance Session File', 
			'.psm1' : u'Windows PowerShell Script Module File', 
			'.ptl' : u'Rational Rose Petal File', 
			'.pty' : u'Rational Property Set', 
			'.pwn' : u'Pawn Source Code File', 
			'.pxd' : u'Pyrex Definition File', 
			'.pxi' : u'Pyrex Include File', 
			'.py' : u'Python Script', 
			'.pyd' : u'Python Dynamic Module', 
			'.pym' : u'PYM Macro Preprocessor File', 
			'.pyw' : u'Python GUI Source File', 
			'.pyx' : u'Pyrex Source Code File', 
			'.qml' : u'QT Meta Language File', 
			'.qpr' : u'FoxPro Generated Query Program', 
			'.qx' : u'Quexal Source Code', 
			'.r' : u'Rez Source Code File', 
			'.r' : u'R Script File', 
			'.r' : u'REBOL Script', 
			'.r' : u'Ratfor Source Code File', 
			'.rav' : u'Rave Reports Project File', 
			'.rb' : u'Real Studio Project', 
			'.rb' : u'Ruby Source Code', 
			'.rbc' : u'Rembo-C Script', 
			'.rbp' : u'Real Studio Project File', 
			'.rbvcp' : u'Real Studio Version Controlled Project', 
			'.rbxs' : u'ROBLOX Script', 
			'.rc' : u'Resource Script', 
			'.rc2' : u'Visual Studio Resources File', 
			'.rdlc' : u'Visual Studio Client Report Definition File', 
			'.reb' : u'REBOL Script File', 
			'.refresh' : u'Visual Studio Refresh File', 
			'.res' : u'Windows Resource File', 
			'.res' : u'C++ Complied Resource Script', 
			'.resjson' : u'Windows JavaScript Resources File', 
			'.resources' : u'Visual Studio Resource File', 
			'.resw' : u'Windows Resources File', 
			'.resx' : u'.NET Managed Resources File', 
			'.rise' : u'RISE Editor Model File', 
			'.rls' : u'Symbian Localization File', 
			'.rnc' : u'RELAX NG Compact Syntax File', 
			'.rodl' : u'RemObjects Definition Language File', 
			'.rotest' : u'RemObjects SDK Test File', 
			'.rotestresult' : u'RemObjects SDK Test Results File', 
			'.rpy' : u'Python Script', 
			'.rs' : u'Rust Source Code File', 
			'.rsrc' : u'Macintosh Resource File', 
			'.rss' : u'Symbian Application Resource File', 
			'.ru' : u'Java Russian Font Properties File', 
			'.rul' : u'InstallShield Rules File', 
			'.rwsnippet' : u'RapidWeaver Snippet File', 
			'.s' : u'Source Code File', 
			'.s19' : u'Motorola S19 File Record', 
			'.sas' : u'SAS Program File', 
			'.sb' : u'Scratch Project File', 
			'.sb' : u'Small Basic Source Code File', 
			'.sb2' : u'Scratch 2.0 Project File', 
			'.sbproj' : u'OpenGL Shader Builder Project', 
			'.sbr' : u'Visual Studio Source Browser Intermediate File', 
			'.sc' : u'SuperCollider Source Code File', 
			'.scc' : u'SourceSafe Source Code Control File', 
			'.scratch' : u'Scratch Project File', 
			'.scriptsuite' : u'AppleScript Script Suite File', 
			'.scriptterminology' : u'AppleScript Script Terminology File', 
			'.sdef' : u'AppleScript Dictionary Document', 
			'.sdl' : u'Service Description Language File', 
			'.sed' : u'Sed Script', 
			'.sem' : u'Alpha Five Set Data Dictionary Memo File', 
			'.set' : u'Alpha Five Set Data Dictionary File', 
			'.setup' : u'CryENGINE Character Setup File', 
			'.sex' : u'Alpha Five Set Data Dictionary Index File', 
			'.sh' : u'Bash Shell Script', 
			'.sjava' : u'Synchronous Java File', 
			'.sll' : u'Static Link Library', 
			'.sln' : u'Visual Studio Solution File', 
			'.slogo' : u'StarLogo Project File', 
			'.slogt' : u'StarLogo Project Template', 
			'.sltng' : u'StarLogo TNG Project File', 
			'.sma' : u'AMX Mod Plugin Source File', 
			'.smali' : u'Android Smali Assembly Language File', 
			'.smf' : u'SkinMagic C/C++ Toolkit File', 
			'.sml' : u'ARC/INFO Simple Macro Language File', 
			'.snippet' : u'Visual Studio IntelliSense Code Snippet', 
			'.so' : u'Shared Library', 
			'.spec' : u'RPM Specification File', 
			'.spt' : u'Cypress Semiconductor Script', 
			'.spt' : u'ESPL Programming File', 
			'.sqlproj' : u'Visual Studio SQL Server Project', 
			'.src' : u'Source Code', 
			'.src.rpm' : u'Red Hat Package Manager Source File', 
			'.ss' : u'SilverStripe Source Code File', 
			'.ssc' : u'SourceSafe Status File', 
			'.ssi' : u'Adobe Dreamweaver Server Side Include File', 
			'.storyboard' : u'Interface Builder Storyboard Document', 
			'.sud' : u'Super Project Analyzer File', 
			'.suo' : u'Visual Studio Solution User Options File', 
			'.sup' : u'Super Project Definition File', 
			'.svn-base' : u'Subversion Base File', 
			'.swc' : u'Flex Components Archive', 
			'.swd' : u'Flash Debug File', 
			'.sym' : u'Symbols File', 
			'.t' : u'Turing Source Code File', 
			'.targets' : u'MSBuild Targets File', 
			'.tcc' : u'C++ Source Code File', 
			'.tcl' : u'Tcl Script', 
			'.tds' : u'Turbo Debugger Symbols File', 
			'.testrunconfig' : u'Visual Studio Test Run Configuration File', 
			'.testsettings' : u'Visual Studio Test Settings File', 
			'.textfactory' : u'BBEdit Text Factory', 
			'.tiprogram' : u'TI-Basic Program File', 
			'.tk' : u'Tk Script', 
			'.tld' : u'Tag Library Descriptor File', 
			'.tlh' : u'Typelib Generated C/C++ Header File', 
			'.tli' : u'Typelib Generated C/C++ Inline File', 
			'.tmlanguage' : u'TextMate Language Grammar File', 
			'.tmpl' : u'BlueJ Default Template', 
			'.tmproj' : u'TextMate Project File', 
			'.tmproject' : u'TextMate Project', 
			'.tns' : u'TI-Nspire Document', 
			'.tpu' : u'Turbo Pascal Unit', 
			'.tpx' : u'Turbo Pascal 7 Unit', 
			'.trx' : u'Visual Studio Test Results File', 
			'.tt' : u'Visual Studio Text Template', 
			'.tu' : u'Turing Source File', 
			'.tur' : u'Turing Program Source File', 
			'.twig' : u'Twig Template', 
			'.ui' : u'User Interface File', 
			'.uml' : u'UML Data Object Model', 
			'.umlclass' : u'UML Class Model', 
			'.v' : u'Verilog Source Code File', 
			'.v' : u'Coq Source Code File', 
			'.vac' : u'Oc2.316s Cakit File', 
			'.vala' : u'Vala Source Code File', 
			'.var' : u'Variable Data', 
			'.vbg' : u'Visual Basic Project Group File', 
			'.vbp' : u'Visual Basic Project File', 
			'.vbproj' : u'Visual Studio Visual Basic Project', 
			'.vbx' : u'Visual Basic Custom Control', 
			'.vbz' : u'Visual Basic Project Template', 
			'.vc' : u'Verge Code File', 
			'.vc4' : u'Visual C++ 4 File', 
			'.vcp' : u'eMbedded Visual C++ Project File', 
			'.vcproj' : u'Visual C++ Project File', 
			'.vcx' : u'Visual Fox Pro Class Library', 
			'.vcxproj' : u'Visual C++ Project', 
			'.vdm' : u'VDM Specification File', 
			'.vdm' : u'VEDIT Macro File', 
			'.vdp' : u'Visual Studio Deployment Project', 
			'.vdproj' : u'Visual Studio Setup and Deployment Project', 
			'.vgc' : u'ViziGen Code Generation Template', 
			'.vhd' : u'VHDL Source File', 
			'.vic' : u'ViziGen Code Import Mappings File', 
			'.vm' : u'Velocity Template', 
			'.vpc' : u'ViziGen Configuration File', 
			'.vsct' : u'Visual Studio Command Table ', 
			'.vsixmanifest' : u'VSIX Manifest', 
			'.vsl' : u'Velocity Template File', 
			'.vsmacros' : u'Visual Studio Binary Macro Project', 
			'.vsmdi' : u'Visual Studio Test Metadata File', 
			'.vsmproj' : u'Visual Studio Text Macro Project', 
			'.vsp' : u'Visual Studio Performance Report File', 
			'.vspf' : u'Visual Studio Performance Filter File', 
			'.vsps' : u'Visual Studio Serialized Performance Report', 
			'.vspscc' : u'Visual Studio Project Source Control File', 
			'.vspx' : u'Visual Studio Performance Report Data File', 
			'.vssscc' : u'Visual Studio Solution Source Control File', 
			'.vsz' : u'Visual Studio Wizard File', 
			'.vtm' : u'Visual Tool Markup Language Document', 
			'.vtml' : u'Visual Tool Markup Language File', 
			'.vtv' : u'Adobe Dreamweaver Validator Configuration File', 
			'.w' : u'OpenEdge Architect Source Code File', 
			'.w32' : u'Win32 Makefile', 
			'.wdgt' : u'Adobe Captivate Widget File', 
			'.wdgtproj' : u'Dashcode Widget Project', 
			'.wdl' : u'World Definition Language Script', 
			'.wdp' : u'Windev Project File', 
			'.wdw' : u'WinDev Window File', 
			'.wid' : u'Visual Studio Widget File', 
			'.winmd' : u'Windows Metadata File', 
			'.wiq' : u'Visual Studio Work Item Query File', 
			'.wixlib' : u'WiX Library File', 
			'.wixmsp' : u'WiX XML Patch File', 
			'.wixmst' : u'WiX Transform File', 
			'.wixobj' : u'WiX Object File', 
			'.wixout' : u'WiX XML Output File', 
			'.wixpdb' : u'WiX Debug File', 
			'.wixproj' : u'WiX Project File', 
			'.worksheet' : u'BBEdit Shell Worksheet File', 
			'.workspace' : u'Code::Blocks Workspace File', 
			'.wowproj' : u'AddOn Studio Project File', 
			'.wpw' : u'WinDev Mobile Window File', 
			'.wsc' : u'Windows Script Component', 
			'.wsp' : u'SharePoint Solution Package', 
			'.wxi' : u'WiX Include File', 
			'.wxl' : u'WiX Localization File', 
			'.wxs' : u'WiX Source File', 
			'.x' : u'Lex Source Code File', 
			'.xaml' : u'XAML File', 
			'.xamlx' : u'Visual Studio Workflow Service File', 
			'.xap' : u'XACT Project', 
			'.xbf' : u'XAML Binary File', 
			'.xcappdata' : u'Xcode App Data File', 
			'.xcarchive' : u'Xcode Archive', 
			'.xcdatamodel' : u'Xcode Core Data Model File', 
			'.xcdatamodeld' : u'Xcode Core Data Model File', 
			'.xcode' : u'Xcode Project', 
			'.xcodeproj' : u'Xcode Project', 
			'.xcsnapshots' : u'Xcode Snapshot', 
			'.xcworkspace' : u'Xcode Workspace File', 
			'.xib' : u'Interface Builder File', 
			'.xoml' : u'Windows Workflow File', 
			'.xpp' : u'X++ Source Code File', 
			'.xq' : u'XQuery File', 
			'.xql' : u'XML Query Language File', 
			'.xqm' : u'XQuery Module', 
			'.xquery' : u'XQuery Source Code File', 
			'.xqy' : u'XQuery Source File', 
			'.xsd' : u'XML Schema Definition', 
			'.xsx' : u'Visual Studio XML Schema Layout File', 
			'.xt' : u'Xdebug Trace File', 
			'.y' : u'Yacc Source File', 
			'.yab' : u'Yabasic Source Code', 
			'.yaml' : u'YAML Document', 
			'.yml' : u'YAML Document', 
			'.yml2' : u'YML Script', 
			'.ymp' : u'YaST Metapackage File', 
			'.ypr' : u'BYOB Project File',}

def walklevel(some_dir, level=1):
	some_dir = some_dir.rstrip(os.path.sep)
	assert os.path.isdir(some_dir)
	num_sep = some_dir.count(os.path.sep)
	
	for root, dirs, files in os.walk(some_dir):

		if 'external' in dirs:
			dirs.remove('external')
		if 'workdir' in dirs:
			dirs.remove('workdir')
		if 'instdir' in dirs:
			dirs.remove('instdir')

		yield root, dirs, files

		num_sep_this = root.count(os.path.sep)

		if num_sep + level <= num_sep_this:
			del dirs[:]

def get_files(path):

	exts = {}

	for root, dirs, files in os.walk(path):

		for f in files:

			file, ext = os.path.splitext(f)
			ext = ext.lower()

			if ext not in exts:
				exts[ext] = 1
			else:
				exts[ext] += 1

	return exts

def write_exts_to_file():

	exts = {}

	for root, dirs, files in walklevel('.', 1):

		for ext, count in get_files(root).items():

			if exts.has_key(ext):
				exts.get(ext).append(root)
			else:
				exts[ext] = [root]

	for k, v in exts.items():

		if not ext_desc.has_key(k):
			continue

		with open('programming_languages.md', 'a') as f:

			f.write('%s - %s\n' % (k, ext_desc.get(k)))
			f.write('------\n\n')

			for e in v:
				f.write(e.replace('./', '') + '\n')

			f.write('\n\n')

def write_lng_to_file():

	for root, dirs, files in walklevel('.', 1):

		with open('programming_languages_by_folder.md', 'a') as f:

			f.write('%s\n------\n\n' % root)

			for ext, count in get_files(root).items():
				if ext_desc.has_key(ext):
					f.write('%s - %s - %d\n' % (ext, ext_desc.get(ext) , count))

			f.write('\n\n')

write_lng_to_file()